name: Hello
on: [push]
env:
  SERVER: Production

jobs:
  my_first_job:
    name: The First Job

    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Download files
        uses: actions/checkout@v2
      - name: Launch CFN
        run: |
          ls -l
          aws --version
          aws cloudformation deploy --template-file ./AWSConfig-01.yml --stack-name github-actions --capabilities CAPABILITY_IAM
        # uname -a
        # echo $SERVER
